[package]
name = "vocab"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.31", features = ["derive"] }
color-eyre = "0.6.3"
crossterm = "0.28.1"
polars = "0.46.0"
polars-core = "0.46.0"
polars-io = "0.46.0"
rand = "0.9.0"
ratatui = "0.29.0"
